import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import { GoogleGenAI } from "@google/genai";

// Load environment variables (silently fail if file missing in production)
dotenv.config({ path: '.env.local', silent: true });

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();

// Middleware
app.use(cors());
app.use(express.json());

// Health Check
app.get('/api/health', (req, res) => {
    res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// API Route
app.post('/api/generate', async (req, res) => {
    // 1. Validation
    const { url } = req.body;
    if (!url) return res.status(400).json({ error: 'URL is required' });

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
        console.error("API Key missing on server");
        return res.status(500).json({ error: 'Server configuration error: API Key missing' });
    }

    try {
        // 2. Setup
        const ai = new GoogleGenAI({ apiKey });
        const today = new Date().toISOString().split('T')[0];
        const cleanUrl = url.replace(/^https?:\/\//, '').replace(/\/$/, '');

        // 3. Prompt Engineering
        // "Candidates" in Gemini API refers to the possible text responses generated by the AI.
        // We structure the prompt to ensure the "first candidate" is always our high-quality answer.
        const prompt = `
ROLE
You are the "Strategic AI Brand Architect & GEO Specialist." Your purpose is to transform raw website data into the industry-leading llms.txt standard. Your output is the "Source of Truth" for LLMs.

OBJECTIVE
Generate a hyper-comprehensive llms.txt file for ${cleanUrl} (Current Date: ${today}).

SEARCH PROTOCOL (MANDATORY)
1. Use the googleSearch tool to explore the domain: ${url}
2. Specifically look for:
   - Core Features & Capabilities
   - API Documentation & Integration details
   - Pricing & Enterprise Plans
   - Brand Positioning & Mission
3. Verify all claims against the retrieved content.

ARCHITECTURAL RULES
- NO SUMMARIZATION: State "The authoritative resource for X is [URL]" instead of summarizing.
- ZERO SHORTCUTS: List ALL features/pages found. No "..." or "etc".
- GEO OPTIMIZATION: Use semantic triples (Subject-Predicate-Object) for descriptions.
- ABSOLUTE PATHS: All links must be full URLs (https://...).

CONTENT HIERARCHY for llms.txt
1. Brand Identity & Positioning
2. Feature & Capability Index
3. Use-Case & Solution Matrix
4. Technical API & Interoperability
5. Citation & Attribution Guidelines
6. Full Resource Directory

Generate the definitive llms.txt file now in valid Markdown.
`;

        // 4. Generation with Retry & Real-time Search
        const generateWithRetry = async (retryCount = 0) => {
            try {
                return await ai.models.generateContent({
                    model: 'gemini-2.5-flash',
                    contents: [{ role: 'user', parts: [{ text: prompt }] }],
                    config: {
                        tools: [{ googleSearch: {} }],
                        maxOutputTokens: 8192,
                        temperature: 0.1, // Low temperature for factual accuracy
                        safetySettings: [ // Permissive settings to prevent blocking legitimate content
                            { category: 'HARM_CATEGORY_HARASSMENT', threshold: 'BLOCK_NONE' },
                            { category: 'HARM_CATEGORY_HATE_SPEECH', threshold: 'BLOCK_NONE' },
                            { category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT', threshold: 'BLOCK_NONE' },
                            { category: 'HARM_CATEGORY_DANGEROUS_CONTENT', threshold: 'BLOCK_NONE' }
                        ]
                    },
                });
            } catch (error) {
                if (error.status === 429 && retryCount < 3) { // Rate Limit Handling
                    const delay = Math.pow(2, retryCount) * 2000;
                    await new Promise(resolve => setTimeout(resolve, delay));
                    return generateWithRetry(retryCount + 1);
                }
                throw error;
            }
        };

        const response = await generateWithRetry();

        // 5. robust Extraction
        // The API returns "candidates" (choices). We take the first one.
        // When tools are used, the text is sometimes nested differently.
        let text = "";
        if (response.candidates?.[0]?.content?.parts) {
            text = response.candidates[0].content.parts.map(p => p.text || "").join("");
        }

        // Fallback
        if (!text && response.text) {
            text = typeof response.text === 'function' ? response.text() : response.text;
        }

        // 6. Cleanup & Response
        text = (text || "No content generated.").trim();

        // Remove markdown code blocks if present
        text = text.replace(/^```markdown\s*/, "").replace(/^```\s*/, "").replace(/\s*```$/, "");
        // Remove "Here is the..." chatty intros
        text = text.replace(/^Here is the.*$/im, '').trim();

        res.json({
            content: text,
            usageMetadata: {
                promptTokenCount: response.usageMetadata?.promptTokenCount || 0,
                candidatesTokenCount: response.usageMetadata?.candidatesTokenCount || 0,
                totalTokenCount: response.usageMetadata?.totalTokenCount || 0,
            }
        });

    } catch (error) {
        console.error("Gemini Generation Error:", error);
        res.status(500).json({ error: 'Failed to generate content. Please try again.' });
    }
});

// Production Static Serving (Managed by Vercel usually, but good fallback)
const isVercel = process.env.VERCEL === '1';
if (!isVercel && (process.env.NODE_ENV === 'production' || process.argv.includes('--production'))) {
    app.use(express.static(path.join(__dirname, 'dist')));
    app.get('*', (req, res) => res.sendFile(path.join(__dirname, 'dist', 'index.html')));
}

export default app;
