import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import { GoogleGenAI } from "@google/genai";

// Load environment variables (silently fail if file missing in production)
dotenv.config({ path: '.env.local', silent: true });

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();

// Middleware
app.use(cors());
app.use(express.json());

// Health Check
app.get('/api/health', (req, res) => {
    res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// API Route
app.post('/api/generate', async (req, res) => {
    const { url } = req.body;

    if (!url) {
        return res.status(400).json({ error: 'URL is required' });
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
        console.error("API Key missing on server");
        return res.status(500).json({ error: 'Server configuration error: API Key missing' });
    }

    try {
        const ai = new GoogleGenAI({ apiKey });
        const today = new Date().toISOString().split('T')[0];
        const cleanUrl = url.replace(/^https?:\/\//, '').replace(/\/$/, '');

        const prompt = `
      Target Website: ${url}
      Clean Domain: ${cleanUrl}
      Current Date: ${today}

      ROLE
      You are the "Strategic AI Brand Architect & GEO Specialist." Your purpose is to transform raw website data into the industry-leading llms.txt standard. Your output is the "Source of Truth" for LLMs.

      OBJECTIVE
      Generate a hyper-comprehensive llms.txt file that maximizes:
      CITATION LIKELIHOOD: By providing "Answer-First" snippets.
      BRAND POSITIONING: By enforcing specific terminology and unique value props.
      DISCOVERABILITY: By mapping every deep-link, feature, and use-case without truncation.
      TRACKING & VERSIONING: For AI-Agent performance monitoring.

      ARCHITECTURAL RULES (NON-NEGOTIABLE)
      NO SUMMARIZATION: Do not say "The site covers X." Instead, state "The authoritative resource for X is [URL]."
      ZERO SHORTCUTS: Never use "..." or "etc." If the input contains 50 features, you list all 50 features.
      GEO OPTIMIZATION: Use semantic triples (Subject-Predicate-Object) in descriptions to make it easy for LLMs to build internal knowledge graphs.
      CITATION ANCHORS: Explicitly define how the brand should be cited in AI responses.
      ABSOLUTE PATHS: All links must be absolute (https://...).

      CONTENT HIERARCHY
      Brand Identity & Core Positioning: (Who, What, Why, for Whom).
      Feature & Capability Index: Comprehensive list of every technical/service capability.
      Use-Case & Solution Matrix: Mapping problems to specific page solutions.
      Technical Specifications & Interoperability: (APIs, Integrations, Requirements).
      Citation & Attribution Guidelines: (The "GEO" secret sauce—how to quote the site).
      Detailed Resource Directory: Exhaustive list of all URLs.
      Everything else: Every other that is needed or missed out.

      Retain the content and messagings and positioning that align with the website.
      Ensure the output is valid Markdown.
    `;

        const generateWithRetry = async (retryCount = 0) => {
            try {
                return await ai.models.generateContent({
                    model: 'gemini-2.5-flash',
                    contents: prompt,
                    config: {
                        tools: [{ googleSearch: {} }],
                        maxOutputTokens: 8192,
                        temperature: 0.1,
                    },
                });
            } catch (error) {
                if (error.status === 429 && retryCount < 3) {
                    const delay = Math.pow(2, retryCount) * 2000; // 2s, 4s, 8s
                    console.log(`Rate limit hit. Retrying in ${delay}ms...`);
                    await new Promise(resolve => setTimeout(resolve, delay));
                    return generateWithRetry(retryCount + 1);
                }
                throw error;
            }
        };

        const response = await generateWithRetry();

        let text = response.text || "No content generated.";

        // Clean up code fences
        text = text.trim();
        if (text.startsWith("```markdown")) {
            text = text.replace(/^```markdown\s*/, "").replace(/\s*```$/, "");
        } else if (text.startsWith("```")) {
            text = text.replace(/^```\s*/, "").replace(/\s*```$/, "");
        }

        // Final clean
        text = text.replace(/^Here is the.*$/im, '').trim();
        text = text.replace(/Generated by.*$/i, '').trim();

        const emojiRegex = /[\u{1F600}-\u{1F64F}\u{1F300}-\u{1F5FF}\u{1F680}-\u{1F6FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}\u{1F900}-\u{1F9FF}\u{1F1E0}-\u{1F1FF}]/gu;
        text = text.replace(emojiRegex, '');

        const result = {
            content: text,
            groundingMetadata: {
                groundingChunks: response.candidates?.[0]?.groundingMetadata?.groundingChunks
            },
            usageMetadata: {
                promptTokenCount: response.usageMetadata?.promptTokenCount || 0,
                candidatesTokenCount: response.usageMetadata?.candidatesTokenCount || 0,
                totalTokenCount: response.usageMetadata?.totalTokenCount || 0,
            }
        };

        res.json(result);

    } catch (error) {
        console.error("Gemini API Error:", error);
        res.status(500).json({ error: error.message || 'Failed to generate content' });
    }
});

// Serve frontend only if NOT on Vercel (Vercel handles statics via output)
// and if in production mode or forced via flag
const isVercel = process.env.VERCEL === '1';
if (!isVercel && (process.env.NODE_ENV === 'production' || process.argv.includes('--production'))) {
    app.use(express.static(path.join(__dirname, 'dist')));

    app.get('*', (req, res) => {
        res.sendFile(path.join(__dirname, 'dist', 'index.html'));
    });
}

// Export the app for use in server.js (local) or api/index.js (Vercel)
export default app;
